# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myImage/images/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuF = QtWidgets.QMenu(self.menuBar)
        self.menuF.setObjectName("menuF")
        self.menuE = QtWidgets.QMenu(self.menuBar)
        self.menuE.setObjectName("menuE")
        self.menuW = QtWidgets.QMenu(self.menuBar)
        self.menuW.setObjectName("menuW")
        self.menuH = QtWidgets.QMenu(self.menuBar)
        self.menuH.setObjectName("menuH")
        self.menuK = QtWidgets.QMenu(self.menuBar)
        self.menuK.setObjectName("menuK")
        self.menu = QtWidgets.QMenu(self.menuK)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myImage/images/quote.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon1)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myImage/images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/myImage/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/myImage/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/myImage/images/saveAs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon5)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/myImage/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/myImage/images/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon7)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/myImage/images/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon8)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/myImage/images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon9)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/myImage/images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon10)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/myImage/images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon11)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCloseAll = QtWidgets.QAction(MainWindow)
        self.actionCloseAll.setObjectName("actionCloseAll")
        self.actionTile = QtWidgets.QAction(MainWindow)
        self.actionTile.setObjectName("actionTile")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/myImage/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon12)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/myImage/images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon13)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/myImage/images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon14)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionHomepage = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/myImage/images/Logo_2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHomepage.setIcon(icon15)
        self.actionHomepage.setObjectName("actionHomepage")
        self.actionProduce = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/myImage/images/machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProduce.setIcon(icon16)
        self.actionProduce.setObjectName("actionProduce")
        self.actionPurch = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/myImage/images/pay_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPurch.setIcon(icon17)
        self.actionPurch.setObjectName("actionPurch")
        self.actionQuality_Assurance = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/myImage/images/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuality_Assurance.setIcon(icon18)
        self.actionQuality_Assurance.setObjectName("actionQuality_Assurance")
        self.actionWarehouse = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/myImage/images/warehouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWarehouse.setIcon(icon19)
        self.actionWarehouse.setObjectName("actionWarehouse")
        self.actionlogistics = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/myImage/images/logistics_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionlogistics.setIcon(icon20)
        self.actionlogistics.setObjectName("actionlogistics")
        self.actionFinance = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/myImage/images/finance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFinance.setIcon(icon21)
        self.actionFinance.setObjectName("actionFinance")
        self.actionTechnology = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/myImage/images/Drawing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTechnology.setIcon(icon22)
        self.actionTechnology.setObjectName("actionTechnology")
        self.actionQuery = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/myImage/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuery.setIcon(icon23)
        self.actionQuery.setObjectName("actionQuery")
        self.actionQuote = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/myImage/images/Sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuote.setIcon(icon24)
        self.actionQuote.setObjectName("actionQuote")
        self.actionCheck = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/myImage/images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheck.setIcon(icon25)
        self.actionCheck.setObjectName("actionCheck")
        self.actionOrder = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/myImage/images/order.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrder.setIcon(icon26)
        self.actionOrder.setObjectName("actionOrder")
        self.actionprint = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/myImage/images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprint.setIcon(icon27)
        self.actionprint.setObjectName("actionprint")
        self.action_query = QtWidgets.QAction(MainWindow)
        self.action_query.setIcon(icon23)
        self.action_query.setObjectName("action_query")
        self.actionAdjust = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/myImage/images/adjust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdjust.setIcon(icon28)
        self.actionAdjust.setObjectName("actionAdjust")
        self.menuF.addAction(self.actionNew)
        self.menuF.addAction(self.actionOpen)
        self.menuF.addAction(self.action_query)
        self.menuF.addSeparator()
        self.menuF.addAction(self.actionSave)
        self.menuF.addAction(self.actionSaveAs)
        self.menuF.addSeparator()
        self.menuF.addAction(self.actionExit)
        self.menuF.addAction(self.actionprint)
        self.menuE.addAction(self.actionUndo)
        self.menuE.addAction(self.actionRedo)
        self.menuE.addSeparator()
        self.menuE.addAction(self.actionCut)
        self.menuE.addAction(self.actionCopy)
        self.menuE.addAction(self.actionPaste)
        self.menuW.addAction(self.actionClose)
        self.menuW.addAction(self.actionCloseAll)
        self.menuW.addSeparator()
        self.menuW.addAction(self.actionTile)
        self.menuW.addAction(self.actionCascade)
        self.menuW.addSeparator()
        self.menuW.addAction(self.actionNext)
        self.menuW.addAction(self.actionPrevious)
        self.menuH.addAction(self.actionAbout)
        self.menu.addAction(self.actionQuote)
        self.menu.addAction(self.actionCheck)
        self.menu.addAction(self.actionAdjust)
        self.menu.addSeparator()
        self.menu.addAction(self.actionOrder)
        self.menuK.addAction(self.actionHomepage)
        self.menuK.addSeparator()
        self.menuK.addAction(self.menu.menuAction())
        self.menuK.addAction(self.actionPurch)
        self.menuK.addAction(self.actionProduce)
        self.menuK.addAction(self.actionQuality_Assurance)
        self.menuK.addAction(self.actionWarehouse)
        self.menuK.addAction(self.actionlogistics)
        self.menuK.addAction(self.actionFinance)
        self.menuK.addAction(self.actionTechnology)
        self.menuK.addAction(self.actionQuery)
        self.menuBar.addAction(self.menuK.menuAction())
        self.menuBar.addAction(self.menuF.menuAction())
        self.menuBar.addAction(self.menuE.menuAction())
        self.menuBar.addAction(self.menuW.menuAction())
        self.menuBar.addAction(self.menuH.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.action_query)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionprint)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "星达ERP"))
        self.menuF.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuE.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menuW.setTitle(_translate("MainWindow", "窗口(&W)"))
        self.menuH.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menuK.setTitle(_translate("MainWindow", "工作(&K)"))
        self.menu.setTitle(_translate("MainWindow", "销售"))
        self.actionNew.setText(_translate("MainWindow", "新建(&N)"))
        self.actionNew.setToolTip(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)..."))
        self.actionOpen.setToolTip(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionSave.setToolTip(_translate("MainWindow", "保存"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "另存为(&A)..."))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "另存为"))
        self.actionExit.setText(_translate("MainWindow", "退出(&X)"))
        self.actionExit.setToolTip(_translate("MainWindow", "退出"))
        self.actionUndo.setText(_translate("MainWindow", "撤销(&U)"))
        self.actionUndo.setToolTip(_translate("MainWindow", "撤销"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "恢复(&R)"))
        self.actionRedo.setToolTip(_translate("MainWindow", "恢复"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "剪切(&T)"))
        self.actionCut.setToolTip(_translate("MainWindow", "剪切"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "复制(&C)"))
        self.actionCopy.setToolTip(_translate("MainWindow", "复制"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴(&P)"))
        self.actionPaste.setToolTip(_translate("MainWindow", "粘贴"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionClose.setText(_translate("MainWindow", "关闭(&O)"))
        self.actionClose.setToolTip(_translate("MainWindow", "关闭"))
        self.actionCloseAll.setText(_translate("MainWindow", "关闭所有窗口(&A)"))
        self.actionCloseAll.setToolTip(_translate("MainWindow", "关闭所有窗口"))
        self.actionTile.setText(_translate("MainWindow", "平铺(&T)"))
        self.actionTile.setToolTip(_translate("MainWindow", "平铺"))
        self.actionCascade.setText(_translate("MainWindow", "层叠(&C)"))
        self.actionCascade.setToolTip(_translate("MainWindow", "层叠"))
        self.actionNext.setText(_translate("MainWindow", "下一个(&X)"))
        self.actionNext.setToolTip(_translate("MainWindow", "下一个"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+Tab"))
        self.actionPrevious.setText(_translate("MainWindow", "前一个(&V)"))
        self.actionPrevious.setToolTip(_translate("MainWindow", "前一个"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Ctrl+Shift+Backtab"))
        self.actionAbout.setText(_translate("MainWindow", "关于ERP(&A)"))
        self.actionAbout.setToolTip(_translate("MainWindow", "关于"))
        self.actionAboutQt.setText(_translate("MainWindow", "关于星达ERP(&Q)"))
        self.actionAboutQt.setToolTip(_translate("MainWindow", "关于ERP"))
        self.actionHomepage.setText(_translate("MainWindow", "首页"))
        self.actionProduce.setText(_translate("MainWindow", "生产"))
        self.actionPurch.setText(_translate("MainWindow", "采购"))
        self.actionQuality_Assurance.setText(_translate("MainWindow", "质保"))
        self.actionWarehouse.setText(_translate("MainWindow", "仓库"))
        self.actionlogistics.setText(_translate("MainWindow", "物流"))
        self.actionFinance.setText(_translate("MainWindow", "财务"))
        self.actionTechnology.setText(_translate("MainWindow", "技术"))
        self.actionQuery.setText(_translate("MainWindow", "查询报表"))
        self.actionQuote.setText(_translate("MainWindow", "报价"))
        self.actionCheck.setText(_translate("MainWindow", "审核"))
        self.actionOrder.setText(_translate("MainWindow", "订单"))
        self.actionprint.setText(_translate("MainWindow", "打印"))
        self.action_query.setText(_translate("MainWindow", "查询"))
        self.actionAdjust.setText(_translate("MainWindow", "调价"))

import erp_rc
import myImage_rc
