# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\erp\wxxd\Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menu_W = QtWidgets.QMenu(self.menubar)
        self.menu_W.setObjectName("menu_W")
        self.menu_S = QtWidgets.QMenu(self.menubar)
        self.menu_S.setObjectName("menu_S")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_K = QtWidgets.QMenu(self.menubar)
        self.menu_K.setObjectName("menu_K")
        self.menu_quote = QtWidgets.QMenu(self.menu_K)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/quote.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_quote.setIcon(icon1)
        self.menu_quote.setObjectName("menu_quote")
        self.menu_produce = QtWidgets.QMenu(self.menu_K)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/images/machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_produce.setIcon(icon2)
        self.menu_produce.setObjectName("menu_produce")
        self.menu_5 = QtWidgets.QMenu(self.menu_K)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/png/images/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_5.setIcon(icon3)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu_K)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/Drawing_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_6.setIcon(icon4)
        self.menu_6.setObjectName("menu_6")
        self.menu_warehouse = QtWidgets.QMenu(self.menu_K)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/png/images/warehouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_warehouse.setIcon(icon5)
        self.menu_warehouse.setObjectName("menu_warehouse")
        self.menu_2 = QtWidgets.QMenu(self.menu_K)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/png/images/transport.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_2.setIcon(icon6)
        self.menu_2.setObjectName("menu_2")
        self.menu_8 = QtWidgets.QMenu(self.menu_K)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/png/images/finance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_8.setIcon(icon7)
        self.menu_8.setObjectName("menu_8")
        self.menu_purchasing = QtWidgets.QMenu(self.menu_K)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/png/images/buy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_purchasing.setIcon(icon8)
        self.menu_purchasing.setObjectName("menu_purchasing")
        self.menu_3 = QtWidgets.QMenu(self.menu_K)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/png/images/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_3.setIcon(icon9)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.NewAction = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/png/images/New.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewAction.setIcon(icon10)
        self.NewAction.setObjectName("NewAction")
        self.OpenAction = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/png/images/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenAction.setIcon(icon11)
        self.OpenAction.setObjectName("OpenAction")
        self.SaveAction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/png/images/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAction.setIcon(icon12)
        self.SaveAction.setObjectName("SaveAction")
        self.action_quote = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/png/images/Sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quote.setIcon(icon13)
        self.action_quote.setObjectName("action_quote")
        self.action_order = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/png/images/order.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_order.setIcon(icon14)
        self.action_order.setObjectName("action_order")
        self.action_plan = QtWidgets.QAction(MainWindow)
        self.action_plan.setObjectName("action_plan")
        self.action_forging = QtWidgets.QAction(MainWindow)
        self.action_forging.setObjectName("action_forging")
        self.action_HT = QtWidgets.QAction(MainWindow)
        self.action_HT.setObjectName("action_HT")
        self.action_machining = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("images/robot_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_machining.setIcon(icon15)
        self.action_machining.setObjectName("action_machining")
        self.actionUT = QtWidgets.QAction(MainWindow)
        self.actionUT.setObjectName("actionUT")
        self.actionPT = QtWidgets.QAction(MainWindow)
        self.actionPT.setObjectName("actionPT")
        self.actionMT = QtWidgets.QAction(MainWindow)
        self.actionMT.setObjectName("actionMT")
        self.actionchongji = QtWidgets.QAction(MainWindow)
        self.actionchongji.setObjectName("actionchongji")
        self.actionlashen = QtWidgets.QAction(MainWindow)
        self.actionlashen.setObjectName("actionlashen")
        self.actionjinxiang = QtWidgets.QAction(MainWindow)
        self.actionjinxiang.setObjectName("actionjinxiang")
        self.actionPMI = QtWidgets.QAction(MainWindow)
        self.actionPMI.setObjectName("actionPMI")
        self.action_drawing = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/png/images/Drawing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_drawing.setIcon(icon16)
        self.action_drawing.setObjectName("action_drawing")
        self.action_technology = QtWidgets.QAction(MainWindow)
        self.action_technology.setObjectName("action_technology")
        self.actionzhibaoshu = QtWidgets.QAction(MainWindow)
        self.actionzhibaoshu.setObjectName("actionzhibaoshu")
        self.actionyuancailiao = QtWidgets.QAction(MainWindow)
        self.actionyuancailiao.setObjectName("actionyuancailiao")
        self.actionwujin = QtWidgets.QAction(MainWindow)
        self.actionwujin.setObjectName("actionwujin")
        self.actionbeijian = QtWidgets.QAction(MainWindow)
        self.actionbeijian.setObjectName("actionbeijian")
        self.action_prepare = QtWidgets.QAction(MainWindow)
        self.action_prepare.setObjectName("action_prepare")
        self.actionkaoqin = QtWidgets.QAction(MainWindow)
        self.actionkaoqin.setObjectName("actionkaoqin")
        self.actionrenshi_2 = QtWidgets.QAction(MainWindow)
        self.actionrenshi_2.setObjectName("actionrenshi_2")
        self.action_steel_products = QtWidgets.QAction(MainWindow)
        self.action_steel_products.setObjectName("action_steel_products")
        self.action_delivery = QtWidgets.QAction(MainWindow)
        self.action_delivery.setObjectName("action_delivery")
        self.actionwulius = QtWidgets.QAction(MainWindow)
        self.actionwulius.setObjectName("actionwulius")
        self.actionscjd = QtWidgets.QAction(MainWindow)
        self.actionscjd.setObjectName("actionscjd")
        self.actionscbb = QtWidgets.QAction(MainWindow)
        self.actionscbb.setObjectName("actionscbb")
        self.actioncwbb = QtWidgets.QAction(MainWindow)
        self.actioncwbb.setObjectName("actioncwbb")
        self.actiontile = QtWidgets.QAction(MainWindow)
        self.actiontile.setObjectName("actiontile")
        self.actioncascade = QtWidgets.QAction(MainWindow)
        self.actioncascade.setObjectName("actioncascade")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.action_home = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/png/images/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_home.setIcon(icon17)
        self.action_home.setObjectName("action_home")
        self.action_quote_check = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/png/images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quote_check.setIcon(icon18)
        self.action_quote_check.setObjectName("action_quote_check")
        self.actionprint = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/png/images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprint.setIcon(icon19)
        self.actionprint.setObjectName("actionprint")
        self.menu_W.addAction(self.actiontile)
        self.menu_W.addAction(self.actioncascade)
        self.menu_H.addAction(self.actionabout)
        self.menu_F.addAction(self.NewAction)
        self.menu_F.addAction(self.OpenAction)
        self.menu_F.addAction(self.SaveAction)
        self.menu_F.addAction(self.actionprint)
        self.menu_quote.addAction(self.action_quote)
        self.menu_quote.addAction(self.action_order)
        self.menu_quote.addAction(self.action_quote_check)
        self.menu_produce.addAction(self.action_plan)
        self.menu_produce.addAction(self.action_prepare)
        self.menu_produce.addAction(self.action_forging)
        self.menu_produce.addAction(self.action_HT)
        self.menu_produce.addAction(self.action_machining)
        self.menu_5.addAction(self.actionUT)
        self.menu_5.addAction(self.actionPT)
        self.menu_5.addAction(self.actionMT)
        self.menu_5.addAction(self.actionchongji)
        self.menu_5.addAction(self.actionlashen)
        self.menu_5.addAction(self.actionjinxiang)
        self.menu_5.addAction(self.actionPMI)
        self.menu_5.addAction(self.actionzhibaoshu)
        self.menu_6.addAction(self.action_drawing)
        self.menu_6.addAction(self.action_technology)
        self.menu_warehouse.addAction(self.actionyuancailiao)
        self.menu_warehouse.addAction(self.actionwujin)
        self.menu_warehouse.addAction(self.actionbeijian)
        self.menu_2.addAction(self.action_delivery)
        self.menu_2.addAction(self.actionwulius)
        self.menu_8.addAction(self.actionkaoqin)
        self.menu_8.addAction(self.actionrenshi_2)
        self.menu_purchasing.addAction(self.action_steel_products)
        self.menu_3.addAction(self.actionscjd)
        self.menu_3.addAction(self.actionscbb)
        self.menu_3.addAction(self.actioncwbb)
        self.menu_K.addAction(self.action_home)
        self.menu_K.addSeparator()
        self.menu_K.addAction(self.menu_quote.menuAction())
        self.menu_K.addAction(self.menu_produce.menuAction())
        self.menu_K.addAction(self.menu_purchasing.menuAction())
        self.menu_K.addAction(self.menu_warehouse.menuAction())
        self.menu_K.addAction(self.menu_8.menuAction())
        self.menu_K.addAction(self.menu_2.menuAction())
        self.menu_K.addAction(self.menu_5.menuAction())
        self.menu_K.addAction(self.menu_6.menuAction())
        self.menu_K.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_K.menuAction())
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_S.menuAction())
        self.menubar.addAction(self.menu_W.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.NewAction)
        self.toolBar.addAction(self.OpenAction)
        self.toolBar.addAction(self.SaveAction)
        self.toolBar.addAction(self.actionprint)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "星达ERP"))
        self.menu_W.setTitle(_translate("MainWindow", "窗口(&w)"))
        self.menu_S.setTitle(_translate("MainWindow", "设置(&S)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_K.setTitle(_translate("MainWindow", "工作(&K)"))
        self.menu_quote.setTitle(_translate("MainWindow", "销售"))
        self.menu_produce.setTitle(_translate("MainWindow", "生产"))
        self.menu_5.setTitle(_translate("MainWindow", "质保"))
        self.menu_6.setTitle(_translate("MainWindow", "技术"))
        self.menu_warehouse.setTitle(_translate("MainWindow", "仓库"))
        self.menu_2.setTitle(_translate("MainWindow", "物流"))
        self.menu_8.setTitle(_translate("MainWindow", "财务"))
        self.menu_purchasing.setTitle(_translate("MainWindow", "采购"))
        self.menu_3.setTitle(_translate("MainWindow", "查询"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.NewAction.setText(_translate("MainWindow", "新建(&N)"))
        self.NewAction.setShortcut(_translate("MainWindow", "Alt+N"))
        self.OpenAction.setText(_translate("MainWindow", "打开(&O)"))
        self.OpenAction.setShortcut(_translate("MainWindow", "Alt+O"))
        self.SaveAction.setText(_translate("MainWindow", "保存(&S)"))
        self.SaveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_quote.setText(_translate("MainWindow", "报价"))
        self.action_order.setText(_translate("MainWindow", "订单"))
        self.action_plan.setText(_translate("MainWindow", "生产计划"))
        self.action_forging.setText(_translate("MainWindow", "锻造"))
        self.action_HT.setText(_translate("MainWindow", "热处理"))
        self.action_machining.setText(_translate("MainWindow", "机械加工"))
        self.actionUT.setText(_translate("MainWindow", "超声检测"))
        self.actionPT.setText(_translate("MainWindow", "渗透检测"))
        self.actionMT.setText(_translate("MainWindow", "磁粉检测"))
        self.actionchongji.setText(_translate("MainWindow", "冲击试验"))
        self.actionlashen.setText(_translate("MainWindow", "拉伸试验"))
        self.actionjinxiang.setText(_translate("MainWindow", "金相检测"))
        self.actionPMI.setText(_translate("MainWindow", "光谱检测"))
        self.action_drawing.setText(_translate("MainWindow", "图纸"))
        self.action_technology.setText(_translate("MainWindow", "工艺"))
        self.actionzhibaoshu.setText(_translate("MainWindow", "质保文件"))
        self.actionyuancailiao.setText(_translate("MainWindow", "原材料库"))
        self.actionwujin.setText(_translate("MainWindow", "五金库"))
        self.actionbeijian.setText(_translate("MainWindow", "备件库"))
        self.action_prepare.setText(_translate("MainWindow", "备料"))
        self.actionkaoqin.setText(_translate("MainWindow", "考勤"))
        self.actionrenshi_2.setText(_translate("MainWindow", "人事"))
        self.action_steel_products.setText(_translate("MainWindow", "钢材"))
        self.action_delivery.setText(_translate("MainWindow", "发货"))
        self.actionwulius.setText(_translate("MainWindow", "物流商"))
        self.actionscjd.setText(_translate("MainWindow", "生产进度"))
        self.actionscbb.setText(_translate("MainWindow", "生产报表"))
        self.actioncwbb.setText(_translate("MainWindow", "财务报表"))
        self.actiontile.setText(_translate("MainWindow", "平铺"))
        self.actioncascade.setText(_translate("MainWindow", "层叠"))
        self.actionabout.setText(_translate("MainWindow", "关于ERP"))
        self.action_home.setText(_translate("MainWindow", "首页"))
        self.action_quote_check.setText(_translate("MainWindow", "报价审核"))
        self.actionprint.setText(_translate("MainWindow", "打印"))

import erp_rc
