# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\Python\ERP\ERPMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 26))
        self.menubar.setObjectName("menubar")
        self.menu_10 = QtWidgets.QMenu(self.menubar)
        self.menu_10.setObjectName("menu_10")
        self.menu_12 = QtWidgets.QMenu(self.menubar)
        self.menu_12.setObjectName("menu_12")
        self.menu_13 = QtWidgets.QMenu(self.menubar)
        self.menu_13.setObjectName("menu_13")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Taskbar = QtWidgets.QTreeWidget(self.widget)
        self.Taskbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Taskbar.sizePolicy().hasHeightForWidth())
        self.Taskbar.setSizePolicy(sizePolicy)
        self.Taskbar.setMinimumSize(QtCore.QSize(180, 300))
        self.Taskbar.setMaximumSize(QtCore.QSize(180, 1880))
        self.Taskbar.setObjectName("Taskbar")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/2 (2).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Taskbar.headerItem().setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/telemarketer_16px_1192881_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/machine_16px_41420_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/measurement_16px_26224_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/buy_32px_1163674_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon4)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/warehouse_16px_573203_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/Finance_16px_529695_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon6)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/logistics_16px_1173566_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon7)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/certificate_mail_safe_16px_4221_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon8)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/Applications_16px_1070727_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon9)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/patientfile_16px_26208_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon10)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.Taskbar)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/query_32px_511256_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon11)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.Taskbar, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.widget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.NewAction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/New64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewAction.setIcon(icon12)
        self.NewAction.setObjectName("NewAction")
        self.OpenAction = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/open_32px_34434.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenAction.setIcon(icon13)
        self.OpenAction.setObjectName("OpenAction")
        self.SaveAction = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/save_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAction.setIcon(icon14)
        self.SaveAction.setObjectName("SaveAction")
        self.action = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("images/job_48px_1207738.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon15)
        self.action.setObjectName("action")
        self.menu.addAction(self.NewAction)
        self.menu.addAction(self.OpenAction)
        self.menu.addAction(self.SaveAction)
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_12.menuAction())
        self.menubar.addAction(self.menu_10.menuAction())
        self.menubar.addAction(self.menu_13.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action)
        self.toolBar.addAction(self.NewAction)
        self.toolBar.addAction(self.OpenAction)
        self.toolBar.addAction(self.SaveAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ERP"))
        self.menu_10.setTitle(_translate("MainWindow", "窗口"))
        self.menu_12.setTitle(_translate("MainWindow", "系统设置"))
        self.menu_13.setTitle(_translate("MainWindow", "帮助"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.Taskbar.headerItem().setText(0, _translate("MainWindow", "无锡星达"))
        __sortingEnabled = self.Taskbar.isSortingEnabled()
        self.Taskbar.setSortingEnabled(False)
        self.Taskbar.topLevelItem(0).setText(0, _translate("MainWindow", "销售"))
        self.Taskbar.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "报价"))
        self.Taskbar.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "订单"))
        self.Taskbar.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "合同"))
        self.Taskbar.topLevelItem(1).setText(0, _translate("MainWindow", "制造"))
        self.Taskbar.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "生产"))
        self.Taskbar.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "生产单"))
        self.Taskbar.topLevelItem(1).child(0).child(1).setText(0, _translate("MainWindow", "生产计划"))
        self.Taskbar.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "锻造"))
        self.Taskbar.topLevelItem(1).child(1).child(0).setText(0, _translate("MainWindow", "本厂锻造"))
        self.Taskbar.topLevelItem(1).child(1).child(1).setText(0, _translate("MainWindow", "外协锻造"))
        self.Taskbar.topLevelItem(1).child(1).child(2).setText(0, _translate("MainWindow", "锻造录入"))
        self.Taskbar.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "热处理"))
        self.Taskbar.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "机械加工"))
        self.Taskbar.topLevelItem(1).child(3).child(0).setText(0, _translate("MainWindow", "车加工"))
        self.Taskbar.topLevelItem(1).child(3).child(1).setText(0, _translate("MainWindow", "线切割"))
        self.Taskbar.topLevelItem(1).child(3).child(2).setText(0, _translate("MainWindow", "本厂加工"))
        self.Taskbar.topLevelItem(1).child(3).child(3).setText(0, _translate("MainWindow", "外协加工"))
        self.Taskbar.topLevelItem(1).child(3).child(4).setText(0, _translate("MainWindow", "机加录入"))
        self.Taskbar.topLevelItem(2).setText(0, _translate("MainWindow", "质检"))
        self.Taskbar.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "硬度"))
        self.Taskbar.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "冲击"))
        self.Taskbar.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "拉伸"))
        self.Taskbar.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "UT"))
        self.Taskbar.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "PT"))
        self.Taskbar.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "MT"))
        self.Taskbar.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "终检"))
        self.Taskbar.topLevelItem(3).setText(0, _translate("MainWindow", "采购"))
        self.Taskbar.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "采购订单"))
        self.Taskbar.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "收货"))
        self.Taskbar.topLevelItem(4).setText(0, _translate("MainWindow", "仓库"))
        self.Taskbar.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "五金库"))
        self.Taskbar.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "成品库"))
        self.Taskbar.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "锻件库"))
        self.Taskbar.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "废品库"))
        self.Taskbar.topLevelItem(5).setText(0, _translate("MainWindow", "财务"))
        self.Taskbar.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "锻造结算"))
        self.Taskbar.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "机加结算"))
        self.Taskbar.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "物流结算"))
        self.Taskbar.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "差旅结算"))
        self.Taskbar.topLevelItem(6).setText(0, _translate("MainWindow", "物流"))
        self.Taskbar.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "发货"))
        self.Taskbar.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "随货试样"))
        self.Taskbar.topLevelItem(7).setText(0, _translate("MainWindow", "质保"))
        self.Taskbar.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "售后"))
        self.Taskbar.topLevelItem(8).setText(0, _translate("MainWindow", "图纸"))
        self.Taskbar.topLevelItem(9).setText(0, _translate("MainWindow", "资源"))
        self.Taskbar.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "人力资源"))
        self.Taskbar.topLevelItem(9).child(1).setText(0, _translate("MainWindow", "客户信息"))
        self.Taskbar.topLevelItem(9).child(2).setText(0, _translate("MainWindow", "协作单位"))
        self.Taskbar.topLevelItem(10).setText(0, _translate("MainWindow", "查询"))
        self.Taskbar.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "报表"))
        self.Taskbar.topLevelItem(10).child(1).setText(0, _translate("MainWindow", "生产进度"))
        self.Taskbar.setSortingEnabled(__sortingEnabled)
        self.NewAction.setText(_translate("MainWindow", "新建"))
        self.NewAction.setShortcut(_translate("MainWindow", "Alt+N"))
        self.OpenAction.setText(_translate("MainWindow", "打开"))
        self.OpenAction.setShortcut(_translate("MainWindow", "Alt+O"))
        self.SaveAction.setText(_translate("MainWindow", "保存"))
        self.SaveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action.setText(_translate("MainWindow", "工作"))

#import ERP_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

