# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\Python\ERP\sell\quote.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fquote(object):
    def setupUi(self, Fquote):
        Fquote.setObjectName("Fquote")
        Fquote.resize(1024, 768)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Fquote)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 2, 7, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PBnew = QtWidgets.QPushButton(Fquote)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/new_file_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBnew.setIcon(icon)
        self.PBnew.setObjectName("PBnew")
        self.horizontalLayout.addWidget(self.PBnew)
        self.PBquery = QtWidgets.QPushButton(Fquote)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/preview_text_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBquery.setIcon(icon1)
        self.PBquery.setObjectName("PBquery")
        self.horizontalLayout.addWidget(self.PBquery)
        self.PBexport = QtWidgets.QPushButton(Fquote)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/export_32px_1096648.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBexport.setIcon(icon2)
        self.PBexport.setObjectName("PBexport")
        self.horizontalLayout.addWidget(self.PBexport)
        self.PBsave = QtWidgets.QPushButton(Fquote)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/save_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBsave.setIcon(icon3)
        self.PBsave.setObjectName("PBsave")
        self.horizontalLayout.addWidget(self.PBsave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Fquote)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(7, -1, 7, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(Fquote)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.CBcorporate = QtWidgets.QComboBox(Fquote)
        self.CBcorporate.setMinimumSize(QtCore.QSize(300, 0))
        self.CBcorporate.setEditable(True)
        self.CBcorporate.setObjectName("CBcorporate")
        self.horizontalLayout_2.addWidget(self.CBcorporate)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_12 = QtWidgets.QLabel(Fquote)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.quotationNo = QtWidgets.QLineEdit(Fquote)
        self.quotationNo.setObjectName("quotationNo")
        self.horizontalLayout_2.addWidget(self.quotationNo)
        self.horizontalLayout_2.setStretch(2, 3)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.TWquote = QtWidgets.QTableWidget(Fquote)
        self.TWquote.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TWquote.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.TWquote.setShowGrid(True)
        self.TWquote.setObjectName("TWquote")
        self.TWquote.setColumnCount(15)
        self.TWquote.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.TWquote.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWquote.setHorizontalHeaderItem(14, item)
        self.verticalLayout_2.addWidget(self.TWquote)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, -1, 35, -1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Fquote)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 3)
        self.label_5 = QtWidgets.QLabel(Fquote)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 4, 1, 2)
        self.label_8 = QtWidgets.QLabel(Fquote)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 9, 1, 2)
        self.quotedate = QtWidgets.QDateEdit(Fquote)
        self.quotedate.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 12, 1), QtCore.QTime(0, 0, 0)))
        self.quotedate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.quotedate.setCalendarPopup(True)
        self.quotedate.setCurrentSectionIndex(2)
        self.quotedate.setTimeSpec(QtCore.Qt.LocalTime)
        self.quotedate.setDate(QtCore.QDate(2018, 12, 1))
        self.quotedate.setObjectName("quotedate")
        self.gridLayout.addWidget(self.quotedate, 1, 11, 1, 1)
        self.label_9 = QtWidgets.QLabel(Fquote)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Fquote)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Fquote)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 10, 1, 2)
        self.label_6 = QtWidgets.QLabel(Fquote)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 2)
        self.lineEdit_6 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 8, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(Fquote)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(Fquote)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 7, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(Fquote)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 2, 11, 1, 1)
        self.label_10 = QtWidgets.QLabel(Fquote)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_5.setBuddy(self.lineEdit_4)
        self.label_8.setBuddy(self.quotedate)
        self.label_9.setBuddy(self.lineEdit_8)
        self.label_2.setBuddy(self.lineEdit)
        self.label_4.setBuddy(self.lineEdit_3)
        self.label_6.setBuddy(self.lineEdit_5)
        self.label_3.setBuddy(self.lineEdit_2)
        self.label_7.setBuddy(self.lineEdit_6)
        self.label_10.setBuddy(self.lineEdit_9)

        self.retranslateUi(Fquote)
        QtCore.QMetaObject.connectSlotsByName(Fquote)

    def retranslateUi(self, Fquote):
        _translate = QtCore.QCoreApplication.translate
        Fquote.setWindowTitle(_translate("Fquote", "报价单"))
        self.PBnew.setText(_translate("Fquote", "新建"))
        self.PBquery.setText(_translate("Fquote", "查询"))
        self.PBexport.setText(_translate("Fquote", "导出"))
        self.PBsave.setText(_translate("Fquote", "保存"))
        self.label.setText(_translate("Fquote", "无锡市星达石化配件有限公司报价单"))
        self.label_11.setText(_translate("Fquote", "公司名称:"))
        self.label_12.setText(_translate("Fquote", "报价单号:"))
        item = self.TWquote.horizontalHeaderItem(0)
        item.setText(_translate("Fquote", "序号"))
        item = self.TWquote.horizontalHeaderItem(1)
        item.setText(_translate("Fquote", "名称"))
        item = self.TWquote.horizontalHeaderItem(2)
        item.setText(_translate("Fquote", "制造标准"))
        item = self.TWquote.horizontalHeaderItem(3)
        item.setText(_translate("Fquote", "规格型号"))
        item = self.TWquote.horizontalHeaderItem(4)
        item.setText(_translate("Fquote", "材质"))
        item = self.TWquote.horizontalHeaderItem(5)
        item.setText(_translate("Fquote", "数量"))
        item = self.TWquote.horizontalHeaderItem(6)
        item.setText(_translate("Fquote", "工作令号"))
        item = self.TWquote.horizontalHeaderItem(7)
        item.setText(_translate("Fquote", "件号"))
        item = self.TWquote.horizontalHeaderItem(8)
        item.setText(_translate("Fquote", "单价"))
        item = self.TWquote.horizontalHeaderItem(9)
        item.setText(_translate("Fquote", "总价(元)"))
        item = self.TWquote.horizontalHeaderItem(10)
        item.setText(_translate("Fquote", "单重(KG)"))
        item = self.TWquote.horizontalHeaderItem(11)
        item.setText(_translate("Fquote", "公斤价"))
        item = self.TWquote.horizontalHeaderItem(12)
        item.setText(_translate("Fquote", "加工费"))
        item = self.TWquote.horizontalHeaderItem(13)
        item.setText(_translate("Fquote", "其他费用"))
        item = self.TWquote.horizontalHeaderItem(14)
        item.setText(_translate("Fquote", "备注"))
        self.label_5.setText(_translate("Fquote", "编制人:"))
        self.lineEdit_5.setText(_translate("Fquote", "0510-85591538"))
        self.label_8.setText(_translate("Fquote", "报价日期:"))
        self.label_9.setText(_translate("Fquote", "交货期:"))
        self.label_2.setText(_translate("Fquote", "金额合计(大写):"))
        self.lineEdit_8.setText(_translate("Fquote", "30天"))
        self.label_4.setText(_translate("Fquote", "总价:"))
        self.label_6.setText(_translate("Fquote", "联系电话:"))
        self.lineEdit_4.setText(_translate("Fquote", "马萍"))
        self.lineEdit_6.setText(_translate("Fquote", "0510-85591761"))
        self.label_3.setText(_translate("Fquote", "总数量:"))
        self.label_7.setText(_translate("Fquote", "传真:"))
        self.lineEdit_9.setText(_translate("Fquote", "5天"))
        self.label_10.setToolTip(_translate("Fquote", "报价有效期"))
        self.label_10.setText(_translate("Fquote", "报价有效期:"))

