# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\pandas\pandasmain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myImage/images/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = DataTableWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuF = QtWidgets.QMenu(self.menuBar)
        self.menuF.setObjectName("menuF")
        self.menuE = QtWidgets.QMenu(self.menuBar)
        self.menuE.setObjectName("menuE")
        self.menuW = QtWidgets.QMenu(self.menuBar)
        self.menuW.setObjectName("menuW")
        self.menuH = QtWidgets.QMenu(self.menuBar)
        self.menuH.setObjectName("menuH")
        self.menuK = QtWidgets.QMenu(self.menuBar)
        self.menuK.setObjectName("menuK")
        self.menu = QtWidgets.QMenu(self.menuK)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myImage/images/quote.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon1)
        self.menu.setObjectName("menu")
        self.menu_5 = QtWidgets.QMenu(self.menuK)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myImage/images/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_5.setIcon(icon2)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu_5)
        self.menu_6.setObjectName("menu_6")
        self.menu_10 = QtWidgets.QMenu(self.menuK)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/myImage/images/warehouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_10.setIcon(icon3)
        self.menu_10.setObjectName("menu_10")
        self.menu_2 = QtWidgets.QMenu(self.menuK)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/myImage/images/machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_2.setIcon(icon4)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/myImage/images/robot_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_4.setIcon(icon5)
        self.menu_4.setObjectName("menu_4")
        self.menu_8 = QtWidgets.QMenu(self.menuK)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/myImage/images/Drawing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_8.setIcon(icon6)
        self.menu_8.setObjectName("menu_8")
        self.menu_9 = QtWidgets.QMenu(self.menuK)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/myImage/images/buy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_9.setIcon(icon7)
        self.menu_9.setObjectName("menu_9")
        self.menu_11 = QtWidgets.QMenu(self.menuK)
        self.menu_11.setObjectName("menu_11")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/myImage/images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/myImage/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon9)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/myImage/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon10)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/myImage/images/saveAs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon11)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/myImage/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon12)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/myImage/images/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon13)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/myImage/images/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon14)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/myImage/images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon15)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/myImage/images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon16)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/myImage/images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon17)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCloseAll = QtWidgets.QAction(MainWindow)
        self.actionCloseAll.setObjectName("actionCloseAll")
        self.actionTile = QtWidgets.QAction(MainWindow)
        self.actionTile.setObjectName("actionTile")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/myImage/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon18)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/myImage/images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon19)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/myImage/images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon20)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionHomepage = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/myImage/images/Logo_2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHomepage.setIcon(icon21)
        self.actionHomepage.setObjectName("actionHomepage")
        self.actionlogistics = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/myImage/images/logistics_32px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionlogistics.setIcon(icon22)
        self.actionlogistics.setObjectName("actionlogistics")
        self.actionFinance = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/myImage/images/finance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFinance.setIcon(icon23)
        self.actionFinance.setObjectName("actionFinance")
        self.actionQuote = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/myImage/images/Sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuote.setIcon(icon24)
        self.actionQuote.setObjectName("actionQuote")
        self.actionCheck = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/myImage/images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheck.setIcon(icon25)
        self.actionCheck.setObjectName("actionCheck")
        self.actionOrder = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/myImage/images/order.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrder.setIcon(icon26)
        self.actionOrder.setObjectName("actionOrder")
        self.actionprint = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/myImage/images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprint.setIcon(icon27)
        self.actionprint.setObjectName("actionprint")
        self.action_query = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/myImage/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_query.setIcon(icon28)
        self.action_query.setObjectName("action_query")
        self.actionAdjust = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/myImage/images/adjust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdjust.setIcon(icon29)
        self.actionAdjust.setObjectName("actionAdjust")
        self.actionPlan = QtWidgets.QAction(MainWindow)
        self.actionPlan.setObjectName("actionPlan")
        self.actionprepare = QtWidgets.QAction(MainWindow)
        self.actionprepare.setObjectName("actionprepare")
        self.actionHT = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/myImage/images/hot_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHT.setIcon(icon30)
        self.actionHT.setObjectName("actionHT")
        self.action1T = QtWidgets.QAction(MainWindow)
        self.action1T.setObjectName("action1T")
        self.action2T = QtWidgets.QAction(MainWindow)
        self.action2T.setObjectName("action2T")
        self.actionyaji = QtWidgets.QAction(MainWindow)
        self.actionyaji.setObjectName("actionyaji")
        self.actionwaixie = QtWidgets.QAction(MainWindow)
        self.actionwaixie.setObjectName("actionwaixie")
        self.actionjingong = QtWidgets.QAction(MainWindow)
        self.actionjingong.setObjectName("actionjingong")
        self.actionjijiaweixie = QtWidgets.QAction(MainWindow)
        self.actionjijiaweixie.setObjectName("actionjijiaweixie")
        self.menu_UT = QtWidgets.QAction(MainWindow)
        self.menu_UT.setObjectName("menu_UT")
        self.menu_PT = QtWidgets.QAction(MainWindow)
        self.menu_PT.setObjectName("menu_PT")
        self.menu_MT = QtWidgets.QAction(MainWindow)
        self.menu_MT.setObjectName("menu_MT")
        self.actionchongji = QtWidgets.QAction(MainWindow)
        self.actionchongji.setObjectName("actionchongji")
        self.actionlasheng = QtWidgets.QAction(MainWindow)
        self.actionlasheng.setObjectName("actionlasheng")
        self.actionyindu = QtWidgets.QAction(MainWindow)
        self.actionyindu.setObjectName("actionyindu")
        self.actionInspection = QtWidgets.QAction(MainWindow)
        self.actionInspection.setObjectName("actionInspection")
        self.actionPMI = QtWidgets.QAction(MainWindow)
        self.actionPMI.setObjectName("actionPMI")
        self.actiongongyi = QtWidgets.QAction(MainWindow)
        self.actiongongyi.setObjectName("actiongongyi")
        self.actionjiagongtuzhi = QtWidgets.QAction(MainWindow)
        self.actionjiagongtuzhi.setObjectName("actionjiagongtuzhi")
        self.actionbiaozhunguifan = QtWidgets.QAction(MainWindow)
        self.actionbiaozhunguifan.setObjectName("actionbiaozhunguifan")
        self.actiongangcai = QtWidgets.QAction(MainWindow)
        self.actiongangcai.setObjectName("actiongangcai")
        self.actionwujin = QtWidgets.QAction(MainWindow)
        self.actionwujin.setObjectName("actionwujin")
        self.actiongangcai_2 = QtWidgets.QAction(MainWindow)
        self.actiongangcai_2.setObjectName("actiongangcai_2")
        self.actionwujin_2 = QtWidgets.QAction(MainWindow)
        self.actionwujin_2.setObjectName("actionwujin_2")
        self.actionshebei = QtWidgets.QAction(MainWindow)
        self.actionshebei.setObjectName("actionshebei")
        self.actionziyuan = QtWidgets.QAction(MainWindow)
        self.actionziyuan.setObjectName("actionziyuan")
        self.actionorder = QtWidgets.QAction(MainWindow)
        self.actionorder.setObjectName("actionorder")
        self.actionwaixie_2 = QtWidgets.QAction(MainWindow)
        self.actionwaixie_2.setObjectName("actionwaixie_2")
        self.actionsc = QtWidgets.QAction(MainWindow)
        self.actionsc.setObjectName("actionsc")
        self.actionScrap = QtWidgets.QAction(MainWindow)
        self.actionScrap.setObjectName("actionScrap")
        self.actionjindu = QtWidgets.QAction(MainWindow)
        self.actionjindu.setObjectName("actionjindu")
        self.actionFgInput = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/myImage/images/enter_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFgInput.setIcon(icon31)
        self.actionFgInput.setObjectName("actionFgInput")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionMchInput = QtWidgets.QAction(MainWindow)
        self.actionMchInput.setObjectName("actionMchInput")
        self.menuF.addAction(self.actionNew)
        self.menuF.addAction(self.actionOpen)
        self.menuF.addAction(self.action_query)
        self.menuF.addSeparator()
        self.menuF.addAction(self.actionSave)
        self.menuF.addAction(self.actionSaveAs)
        self.menuF.addSeparator()
        self.menuF.addAction(self.actionExit)
        self.menuF.addAction(self.actionprint)
        self.menuE.addAction(self.actionUndo)
        self.menuE.addAction(self.actionRedo)
        self.menuE.addSeparator()
        self.menuE.addAction(self.actionCut)
        self.menuE.addAction(self.actionCopy)
        self.menuE.addAction(self.actionPaste)
        self.menuW.addAction(self.actionClose)
        self.menuW.addAction(self.actionCloseAll)
        self.menuW.addSeparator()
        self.menuW.addAction(self.actionTile)
        self.menuW.addAction(self.actionCascade)
        self.menuW.addSeparator()
        self.menuW.addAction(self.actionNext)
        self.menuW.addAction(self.actionPrevious)
        self.menuH.addAction(self.actionAbout)
        self.menu.addAction(self.actionQuote)
        self.menu.addAction(self.actionCheck)
        self.menu.addAction(self.actionAdjust)
        self.menu.addSeparator()
        self.menu.addAction(self.actionOrder)
        self.menu_6.addAction(self.menu_UT)
        self.menu_6.addAction(self.menu_PT)
        self.menu_6.addAction(self.menu_MT)
        self.menu_6.addAction(self.actionchongji)
        self.menu_6.addAction(self.actionlasheng)
        self.menu_6.addAction(self.actionyindu)
        self.menu_5.addAction(self.actionPMI)
        self.menu_5.addAction(self.menu_6.menuAction())
        self.menu_5.addAction(self.actionInspection)
        self.menu_10.addAction(self.actiongangcai_2)
        self.menu_10.addAction(self.actionwujin_2)
        self.menu_10.addAction(self.actionshebei)
        self.menu_3.addAction(self.action1T)
        self.menu_3.addAction(self.action2T)
        self.menu_3.addAction(self.actionyaji)
        self.menu_3.addAction(self.actionwaixie)
        self.menu_3.addAction(self.actionFgInput)
        self.menu_4.addAction(self.actionjingong)
        self.menu_4.addAction(self.actionjijiaweixie)
        self.menu_4.addAction(self.actionMchInput)
        self.menu_2.addAction(self.actionPlan)
        self.menu_2.addAction(self.actionprepare)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.actionHT)
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionScrap)
        self.menu_8.addAction(self.actiongongyi)
        self.menu_8.addAction(self.actionjiagongtuzhi)
        self.menu_8.addAction(self.actionbiaozhunguifan)
        self.menu_9.addAction(self.actiongangcai)
        self.menu_9.addAction(self.actionwujin)
        self.menu_11.addAction(self.actionorder)
        self.menu_11.addAction(self.actionwaixie_2)
        self.menu_11.addAction(self.actionsc)
        self.menu_11.addAction(self.actionjindu)
        self.menuK.addAction(self.actionHomepage)
        self.menuK.addSeparator()
        self.menuK.addAction(self.menu.menuAction())
        self.menuK.addAction(self.menu_2.menuAction())
        self.menuK.addAction(self.menu_5.menuAction())
        self.menuK.addAction(self.menu_9.menuAction())
        self.menuK.addAction(self.menu_10.menuAction())
        self.menuK.addAction(self.actionlogistics)
        self.menuK.addAction(self.actionFinance)
        self.menuK.addAction(self.menu_8.menuAction())
        self.menuK.addAction(self.menu_11.menuAction())
        self.menuK.addAction(self.actionziyuan)
        self.menuBar.addAction(self.menuK.menuAction())
        self.menuBar.addAction(self.menuF.menuAction())
        self.menuBar.addAction(self.menuE.menuAction())
        self.menuBar.addAction(self.menuW.menuAction())
        self.menuBar.addAction(self.menuH.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.action_query)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionprint)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "星达ERP"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))
        self.menuF.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuE.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menuW.setTitle(_translate("MainWindow", "窗口(&W)"))
        self.menuH.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menuK.setTitle(_translate("MainWindow", "工作(&K)"))
        self.menu.setTitle(_translate("MainWindow", "销售"))
        self.menu_5.setTitle(_translate("MainWindow", "质保"))
        self.menu_6.setTitle(_translate("MainWindow", "力学性能"))
        self.menu_10.setTitle(_translate("MainWindow", "仓库"))
        self.menu_2.setTitle(_translate("MainWindow", "生产"))
        self.menu_3.setTitle(_translate("MainWindow", "锻造"))
        self.menu_4.setTitle(_translate("MainWindow", "机加工"))
        self.menu_8.setTitle(_translate("MainWindow", "技术"))
        self.menu_9.setTitle(_translate("MainWindow", "采购"))
        self.menu_11.setTitle(_translate("MainWindow", "查询报表"))
        self.actionNew.setText(_translate("MainWindow", "新建(&N)"))
        self.actionNew.setToolTip(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)..."))
        self.actionOpen.setToolTip(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionSave.setToolTip(_translate("MainWindow", "保存"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "另存为(&A)..."))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "另存为"))
        self.actionExit.setText(_translate("MainWindow", "退出(&X)"))
        self.actionExit.setToolTip(_translate("MainWindow", "退出"))
        self.actionUndo.setText(_translate("MainWindow", "撤销(&U)"))
        self.actionUndo.setToolTip(_translate("MainWindow", "撤销"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "恢复(&R)"))
        self.actionRedo.setToolTip(_translate("MainWindow", "恢复"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "剪切(&T)"))
        self.actionCut.setToolTip(_translate("MainWindow", "剪切"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "复制(&C)"))
        self.actionCopy.setToolTip(_translate("MainWindow", "复制"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴(&P)"))
        self.actionPaste.setToolTip(_translate("MainWindow", "粘贴"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionClose.setText(_translate("MainWindow", "关闭(&O)"))
        self.actionClose.setToolTip(_translate("MainWindow", "关闭"))
        self.actionCloseAll.setText(_translate("MainWindow", "关闭所有窗口(&A)"))
        self.actionCloseAll.setToolTip(_translate("MainWindow", "关闭所有窗口"))
        self.actionTile.setText(_translate("MainWindow", "平铺(&T)"))
        self.actionTile.setToolTip(_translate("MainWindow", "平铺"))
        self.actionCascade.setText(_translate("MainWindow", "层叠(&C)"))
        self.actionCascade.setToolTip(_translate("MainWindow", "层叠"))
        self.actionNext.setText(_translate("MainWindow", "下一个(&X)"))
        self.actionNext.setToolTip(_translate("MainWindow", "下一个"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+Tab"))
        self.actionPrevious.setText(_translate("MainWindow", "前一个(&V)"))
        self.actionPrevious.setToolTip(_translate("MainWindow", "前一个"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Ctrl+Shift+Backtab"))
        self.actionAbout.setText(_translate("MainWindow", "关于ERP(&A)"))
        self.actionAbout.setToolTip(_translate("MainWindow", "关于"))
        self.actionAboutQt.setText(_translate("MainWindow", "关于星达ERP(&Q)"))
        self.actionAboutQt.setToolTip(_translate("MainWindow", "关于ERP"))
        self.actionHomepage.setText(_translate("MainWindow", "首页"))
        self.actionlogistics.setText(_translate("MainWindow", "物流"))
        self.actionFinance.setText(_translate("MainWindow", "财务"))
        self.actionQuote.setText(_translate("MainWindow", "报价"))
        self.actionCheck.setText(_translate("MainWindow", "审核"))
        self.actionOrder.setText(_translate("MainWindow", "订单"))
        self.actionprint.setText(_translate("MainWindow", "打印"))
        self.action_query.setText(_translate("MainWindow", "查询"))
        self.actionAdjust.setText(_translate("MainWindow", "调价"))
        self.actionPlan.setText(_translate("MainWindow", "计划排产"))
        self.actionprepare.setText(_translate("MainWindow", "备料"))
        self.actionHT.setText(_translate("MainWindow", "热处理"))
        self.action1T.setText(_translate("MainWindow", "1T"))
        self.action2T.setText(_translate("MainWindow", "2T"))
        self.actionyaji.setText(_translate("MainWindow", "压机"))
        self.actionwaixie.setText(_translate("MainWindow", "锻造外协"))
        self.actionjingong.setText(_translate("MainWindow", "金工车间"))
        self.actionjijiaweixie.setText(_translate("MainWindow", "机加外协"))
        self.menu_UT.setText(_translate("MainWindow", "UT"))
        self.menu_PT.setText(_translate("MainWindow", "PT"))
        self.menu_MT.setText(_translate("MainWindow", "MT"))
        self.actionchongji.setText(_translate("MainWindow", "冲击"))
        self.actionlasheng.setText(_translate("MainWindow", "拉伸"))
        self.actionyindu.setText(_translate("MainWindow", "硬度"))
        self.actionInspection.setText(_translate("MainWindow", "出厂检验"))
        self.actionPMI.setText(_translate("MainWindow", "PMI"))
        self.actiongongyi.setText(_translate("MainWindow", "工艺流程"))
        self.actionjiagongtuzhi.setText(_translate("MainWindow", "加工图纸"))
        self.actionbiaozhunguifan.setText(_translate("MainWindow", "标准规范"))
        self.actiongangcai.setText(_translate("MainWindow", "钢材"))
        self.actionwujin.setText(_translate("MainWindow", "五金"))
        self.actiongangcai_2.setText(_translate("MainWindow", "钢材台账"))
        self.actionwujin_2.setText(_translate("MainWindow", "五金台账"))
        self.actionshebei.setText(_translate("MainWindow", "设备台账"))
        self.actionziyuan.setText(_translate("MainWindow", "资源管理"))
        self.actionorder.setText(_translate("MainWindow", "合同报表"))
        self.actionwaixie_2.setText(_translate("MainWindow", "外协报表"))
        self.actionsc.setText(_translate("MainWindow", "生产报表"))
        self.actionScrap.setText(_translate("MainWindow", "报废"))
        self.actionjindu.setText(_translate("MainWindow", "生产进度"))
        self.actionFgInput.setText(_translate("MainWindow", "锻造进度录入"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.actionMchInput.setText(_translate("MainWindow", "机加进度录入"))

from qtpandas.views.DataTableView import DataTableWidget
# import myImage_rc
