# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\Python\ERP\ERP.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 141, 651))
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 1080))
        self.treeWidget.setObjectName("treeWidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/2 (2).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget.headerItem().setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/telemarketer_16px_1192881_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/machine_16px_41420_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/measurement_16px_26224_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/buy_32px_1163674_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon4)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/warehouse_16px_573203_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/Finance_16px_529695_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon6)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/logistics_16px_1173566_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon7)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/certificate_mail_safe_16px_4221_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon8)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/Applications_16px_1070727_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon9)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/patientfile_16px_26208_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon10)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/query_32px_511256_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon11)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 0, 871, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../Downloads/search_query_document_32px_519936_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 3, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(160, 379, 871, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 26))
        self.menubar.setObjectName("menubar")
        self.menu_10 = QtWidgets.QMenu(self.menubar)
        self.menu_10.setObjectName("menu_10")
        self.menu_12 = QtWidgets.QMenu(self.menubar)
        self.menu_12.setObjectName("menu_12")
        self.menu_13 = QtWidgets.QMenu(self.menubar)
        self.menu_13.setObjectName("menu_13")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.NewAction = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../Pictures/ICO/New.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewAction.setIcon(icon13)
        self.NewAction.setObjectName("NewAction")
        self.OpenAction = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("images/Open64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenAction.setIcon(icon14)
        self.OpenAction.setObjectName("OpenAction")
        self.SaveAction = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../../Pictures/ICO/disk_save_all_32px_4650_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAction.setIcon(icon15)
        self.SaveAction.setObjectName("SaveAction")
        self.menu.addAction(self.NewAction)
        self.menu.addAction(self.OpenAction)
        self.menu.addAction(self.SaveAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_12.menuAction())
        self.menubar.addAction(self.menu_10.menuAction())
        self.menubar.addAction(self.menu_13.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.NewAction)
        self.toolBar.addAction(self.OpenAction)
        self.toolBar.addAction(self.SaveAction)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ERP"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "无锡星达"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "销售"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "报价"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "订单"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "合同"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "制造"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "生产"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "生产单"))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, _translate("MainWindow", "生产计划"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "锻造"))
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, _translate("MainWindow", "本厂锻造"))
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, _translate("MainWindow", "外协锻造"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "热处理"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "机械加工"))
        self.treeWidget.topLevelItem(1).child(3).child(0).setText(0, _translate("MainWindow", "车加工"))
        self.treeWidget.topLevelItem(1).child(3).child(1).setText(0, _translate("MainWindow", "线切割"))
        self.treeWidget.topLevelItem(1).child(3).child(2).setText(0, _translate("MainWindow", "本厂加工"))
        self.treeWidget.topLevelItem(1).child(3).child(3).setText(0, _translate("MainWindow", "外协加工"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "质检"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "硬度"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "冲击"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "拉伸"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "UT"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "PT"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "MT"))
        self.treeWidget.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "终检"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "采购"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "采购订单"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "收货"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "仓库"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "五金库"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "成品库"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "锻件库"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "废品库"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "财务"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "锻造结算"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "机加结算"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "物流结算"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "差旅结算"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "物流"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "发货"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "随货试样"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "质保"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "售后"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "图纸"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "资源"))
        self.treeWidget.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "人力资源"))
        self.treeWidget.topLevelItem(9).child(1).setText(0, _translate("MainWindow", "客户信息"))
        self.treeWidget.topLevelItem(9).child(2).setText(0, _translate("MainWindow", "协作单位"))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "查询"))
        self.treeWidget.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "报表"))
        self.treeWidget.topLevelItem(10).child(1).setText(0, _translate("MainWindow", "生产进度"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "工作区"))
        self.pushButton_2.setText(_translate("MainWindow", "修改"))
        self.pushButton_3.setText(_translate("MainWindow", "退出"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu_10.setTitle(_translate("MainWindow", "窗口"))
        self.menu_12.setTitle(_translate("MainWindow", "系统设置"))
        self.menu_13.setTitle(_translate("MainWindow", "帮助"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.NewAction.setText(_translate("MainWindow", "新建"))
        self.NewAction.setShortcut(_translate("MainWindow", "Alt+N"))
        self.OpenAction.setText(_translate("MainWindow", "打开"))
        self.OpenAction.setShortcut(_translate("MainWindow", "Alt+O"))
        self.SaveAction.setText(_translate("MainWindow", "保存"))
        self.SaveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

