# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\produce\orderlist.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 768)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(488, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmbState = QtWidgets.QComboBox(Dialog)
        self.cmbState.setMinimumSize(QtCore.QSize(100, 26))
        self.cmbState.setObjectName("cmbState")
        self.horizontalLayout.addWidget(self.cmbState)
        self.cmbCO = QtWidgets.QComboBox(Dialog)
        self.cmbCO.setMinimumSize(QtCore.QSize(100, 26))
        self.cmbCO.setEditable(False)
        self.cmbCO.setObjectName("cmbCO")
        self.horizontalLayout.addWidget(self.cmbCO)
        self.cmbNO = QtWidgets.QComboBox(Dialog)
        self.cmbNO.setMinimumSize(QtCore.QSize(100, 26))
        self.cmbNO.setObjectName("cmbNO")
        self.horizontalLayout.addWidget(self.cmbNO)
        self.btnQuery = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myImage/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuery.setIcon(icon)
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout.addWidget(self.btnQuery)
        self.btnExport = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myImage/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExport.setIcon(icon1)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout.addWidget(self.btnExport)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myImage/images/save_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon2)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.horizontalLayout.setStretch(0, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(352, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 4, 1, 1)
        self.tblwgtOrderList = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblwgtOrderList.sizePolicy().hasHeightForWidth())
        self.tblwgtOrderList.setSizePolicy(sizePolicy)
        self.tblwgtOrderList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblwgtOrderList.setObjectName("tblwgtOrderList")
        self.tblwgtOrderList.setColumnCount(0)
        self.tblwgtOrderList.setRowCount(0)
        self.tblwgtOrderList.horizontalHeader().setStretchLastSection(True)
        self.tblwgtOrderList.verticalHeader().setVisible(False)
        self.tblwgtOrderList.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblwgtOrderList, 3, 0, 1, 5)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 2, 1, 3)
        self.gridLayout.setRowStretch(3, 4)
        self.gridLayout.setRowStretch(4, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnQuery.setText(_translate("Dialog", "查询"))
        self.btnExport.setText(_translate("Dialog", "导出"))
        self.btnSave.setText(_translate("Dialog", "保存"))
        self.label.setText(_translate("Dialog", "订单明细查询"))
        self.label_2.setText(_translate("Dialog", "客户名称:"))
        self.label_3.setText(_translate("Dialog", "生产编号:"))
        self.tblwgtOrderList.setToolTip(_translate("Dialog", "订单明细"))
        self.textEdit.setToolTip(_translate("Dialog", "技术要求"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "技术要求:"))

import myImage_rc
