# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\sale\order.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetOrder(object):
    def setupUi(self, WidgetOrder):
        WidgetOrder.setObjectName("WidgetOrder")
        WidgetOrder.resize(1024, 768)
        WidgetOrder.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetOrder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(488, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cob_CO = QtWidgets.QComboBox(WidgetOrder)
        self.cob_CO.setMinimumSize(QtCore.QSize(100, 26))
        self.cob_CO.setEditable(False)
        self.cob_CO.setObjectName("cob_CO")
        self.horizontalLayout.addWidget(self.cob_CO)
        self.cob_NO = QtWidgets.QComboBox(WidgetOrder)
        self.cob_NO.setMinimumSize(QtCore.QSize(100, 26))
        self.cob_NO.setObjectName("cob_NO")
        self.horizontalLayout.addWidget(self.cob_NO)
        self.PBquery = QtWidgets.QPushButton(WidgetOrder)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBquery.setIcon(icon)
        self.PBquery.setObjectName("PBquery")
        self.horizontalLayout.addWidget(self.PBquery)
        self.PBexport = QtWidgets.QPushButton(WidgetOrder)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBexport.setIcon(icon1)
        self.PBexport.setObjectName("PBexport")
        self.horizontalLayout.addWidget(self.PBexport)
        self.PBsave = QtWidgets.QPushButton(WidgetOrder)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/images/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBsave.setIcon(icon2)
        self.PBsave.setObjectName("PBsave")
        self.horizontalLayout.addWidget(self.PBsave)
        self.horizontalLayout.setStretch(0, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(WidgetOrder)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_1 = QtWidgets.QLabel(WidgetOrder)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 0, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(200, 28))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_2.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(508, 46, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 2, 1)
        self.label_3 = QtWidgets.QLabel(WidgetOrder)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(WidgetOrder)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(WidgetOrder)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 4, 1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.TW_order = QtWidgets.QTableWidget(WidgetOrder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TW_order.sizePolicy().hasHeightForWidth())
        self.TW_order.setSizePolicy(sizePolicy)
        self.TW_order.setObjectName("TW_order")
        self.TW_order.setColumnCount(0)
        self.TW_order.setRowCount(0)
        self.TW_order.horizontalHeader().setStretchLastSection(True)
        self.TW_order.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.TW_order)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(WidgetOrder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 28))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(WidgetOrder)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(WidgetOrder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(150, 28))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(WidgetOrder)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(150, 28))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(WidgetOrder)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 8, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 9, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(WidgetOrder)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 1, 0, 1, 10)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit = QtWidgets.QTextEdit(WidgetOrder)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout.setStretch(3, 5)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(WidgetOrder)
        QtCore.QMetaObject.connectSlotsByName(WidgetOrder)

    def retranslateUi(self, WidgetOrder):
        _translate = QtCore.QCoreApplication.translate
        WidgetOrder.setWindowTitle(_translate("WidgetOrder", "订单合同"))
        self.PBquery.setText(_translate("WidgetOrder", "查询"))
        self.PBexport.setText(_translate("WidgetOrder", "导出"))
        self.PBsave.setText(_translate("WidgetOrder", "保存"))
        self.label.setText(_translate("WidgetOrder", "工  业  品  买  卖  合  同"))
        self.label_1.setText(_translate("WidgetOrder", "卖方:"))
        self.lineEdit_1.setText(_translate("WidgetOrder", "无锡市星达石化配件有限公司"))
        self.label_3.setText(_translate("WidgetOrder", "生产编号:"))
        self.label_2.setText(_translate("WidgetOrder", "买方:"))
        self.label_4.setText(_translate("WidgetOrder", "合同编号:"))
        self.TW_order.setToolTip(_translate("WidgetOrder", "报价清单"))
        self.comboBox.setCurrentText(_translate("WidgetOrder", "选择销售代表"))
        self.label_7.setText(_translate("WidgetOrder", "签订日期:"))
        self.lineEdit_5.setInputMask(_translate("WidgetOrder", "0000-00-00"))
        self.label_5.setText(_translate("WidgetOrder", "总数量:"))
        self.label_10.setText(_translate("WidgetOrder", "总金额:"))
        self.lineEdit_7.setPlaceholderText(_translate("WidgetOrder", "总金额..."))
        self.lineEdit_8.setPlaceholderText(_translate("WidgetOrder", "送货地址:"))
        self.textEdit.setPlaceholderText(_translate("WidgetOrder", "技术要求:"))

import myImage_rc
