# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\produce\plan.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wgt_plan(object):
    def setupUi(self, wgt_plan):
        wgt_plan.setObjectName("wgt_plan")
        wgt_plan.resize(1024, 768)
        wgt_plan.setToolTip("")
        self.gridLayout = QtWidgets.QGridLayout(wgt_plan)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmbCO = QtWidgets.QComboBox(wgt_plan)
        self.cmbCO.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbCO.setEditable(True)
        self.cmbCO.setObjectName("cmbCO")
        self.horizontalLayout.addWidget(self.cmbCO)
        self.pbtnQuery = QtWidgets.QPushButton(wgt_plan)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myImage/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnQuery.setIcon(icon)
        self.pbtnQuery.setObjectName("pbtnQuery")
        self.horizontalLayout.addWidget(self.pbtnQuery)
        self.pbtnExport = QtWidgets.QPushButton(wgt_plan)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myImage/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnExport.setIcon(icon1)
        self.pbtnExport.setObjectName("pbtnExport")
        self.horizontalLayout.addWidget(self.pbtnExport)
        self.pbtnSave = QtWidgets.QPushButton(wgt_plan)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myImage/images/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnSave.setIcon(icon2)
        self.pbtnSave.setObjectName("pbtnSave")
        self.horizontalLayout.addWidget(self.pbtnSave)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.label_9 = QtWidgets.QLabel(wgt_plan)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(wgt_plan)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(wgt_plan)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(501, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(wgt_plan)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(wgt_plan)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 4, 1, 1)
        self.tblwgt = QtWidgets.QTableWidget(wgt_plan)
        self.tblwgt.setObjectName("tblwgt")
        self.tblwgt.setColumnCount(0)
        self.tblwgt.setRowCount(0)
        self.gridLayout.addWidget(self.tblwgt, 3, 0, 1, 5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(638, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(wgt_plan)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(wgt_plan)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(wgt_plan)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(wgt_plan)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(wgt_plan)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(wgt_plan)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(wgt_plan)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(wgt_plan)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 2, 1, 1, 4)
        self.gridLayout_2.setColumnStretch(2, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 5)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setRowStretch(3, 3)
        self.gridLayout.setRowStretch(4, 1)

        self.retranslateUi(wgt_plan)
        QtCore.QMetaObject.connectSlotsByName(wgt_plan)

    def retranslateUi(self, wgt_plan):
        _translate = QtCore.QCoreApplication.translate
        wgt_plan.setWindowTitle(_translate("wgt_plan", "生产单"))
        self.cmbCO.setToolTip(_translate("wgt_plan", "选择公司名称"))
        self.cmbCO.setCurrentText(_translate("wgt_plan", "选择公司名称"))
        self.pbtnQuery.setText(_translate("wgt_plan", "查询"))
        self.pbtnExport.setText(_translate("wgt_plan", "导出"))
        self.pbtnSave.setText(_translate("wgt_plan", "保存"))
        self.label_9.setText(_translate("wgt_plan", "生产计划-->锻造排单"))
        self.label.setText(_translate("wgt_plan", "客户代码:"))
        self.label_2.setText(_translate("wgt_plan", "生产编号:"))
        self.label_7.setText(_translate("wgt_plan", "总 数 量:"))
        self.label_4.setText(_translate("wgt_plan", "编 制 人:"))
        self.lineEdit_4.setText(_translate("wgt_plan", "陈淑娴"))
        self.label_6.setText(_translate("wgt_plan", "制单日期:"))
        self.lineEdit_5.setInputMask(_translate("wgt_plan", "0000-00-00"))
        self.label_5.setText(_translate("wgt_plan", "技术要求:"))
        self.textEdit.setHtml(_translate("wgt_plan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9.07563pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.07563pt;\"><br /></p></body></html>"))

import myImage_rc
