# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\erp\wxxd\sale\quote_check.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Quote_check(object):
    def setupUi(self, Quote_check):
        Quote_check.setObjectName("Quote_check")
        Quote_check.resize(1024, 768)
        Quote_check.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Quote_check)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_edit = QtWidgets.QPushButton(Quote_check)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/modify_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.cbo_group = QtWidgets.QComboBox(Quote_check)
        self.cbo_group.setMinimumSize(QtCore.QSize(0, 26))
        self.cbo_group.setObjectName("cbo_group")
        self.horizontalLayout.addWidget(self.cbo_group)
        self.cbo_filter = QtWidgets.QComboBox(Quote_check)
        self.cbo_filter.setMinimumSize(QtCore.QSize(0, 26))
        self.cbo_filter.setCurrentText("")
        self.cbo_filter.setObjectName("cbo_filter")
        self.horizontalLayout.addWidget(self.cbo_filter)
        self.btn_query = QtWidgets.QPushButton(Quote_check)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/file_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_query.setIcon(icon1)
        self.btn_query.setObjectName("btn_query")
        self.horizontalLayout.addWidget(self.btn_query)
        self.Line_search = QtWidgets.QLineEdit(Quote_check)
        self.Line_search.setMinimumSize(QtCore.QSize(0, 28))
        self.Line_search.setText("")
        self.Line_search.setClearButtonEnabled(True)
        self.Line_search.setObjectName("Line_search")
        self.horizontalLayout.addWidget(self.Line_search)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Quote_list = QtWidgets.QTableWidget(Quote_check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quote_list.sizePolicy().hasHeightForWidth())
        self.Quote_list.setSizePolicy(sizePolicy)
        self.Quote_list.setObjectName("Quote_list")
        self.Quote_list.setColumnCount(7)
        self.Quote_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_list.setHorizontalHeaderItem(6, item)
        self.Quote_list.horizontalHeader().setStretchLastSection(True)
        self.Quote_list.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.Quote_list)
        self.Quote_detail = QtWidgets.QTableWidget(Quote_check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quote_detail.sizePolicy().hasHeightForWidth())
        self.Quote_detail.setSizePolicy(sizePolicy)
        self.Quote_detail.setObjectName("Quote_detail")
        self.Quote_detail.setColumnCount(17)
        self.Quote_detail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.Quote_detail.setHorizontalHeaderItem(16, item)
        self.verticalLayout.addWidget(self.Quote_detail)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(Quote_check)
        QtCore.QMetaObject.connectSlotsByName(Quote_check)

    def retranslateUi(self, Quote_check):
        _translate = QtCore.QCoreApplication.translate
        Quote_check.setWindowTitle(_translate("Quote_check", "报价审核"))
        self.btn_edit.setToolTip(_translate("Quote_check", "修改报价"))
        self.btn_edit.setText(_translate("Quote_check", "修改"))
        self.cbo_group.setToolTip(_translate("Quote_check", "分组"))
        self.cbo_filter.setToolTip(_translate("Quote_check", "审核结果"))
        self.btn_query.setText(_translate("Quote_check", "查询"))
        self.Line_search.setToolTip(_translate("Quote_check", "搜索"))
        self.Line_search.setPlaceholderText(_translate("Quote_check", "搜索...."))
        self.Quote_list.setToolTip(_translate("Quote_check", "报价清单"))
        item = self.Quote_list.horizontalHeaderItem(0)
        item.setText(_translate("Quote_check", "公司名称"))
        item = self.Quote_list.horizontalHeaderItem(1)
        item.setText(_translate("Quote_check", "报价单号"))
        item = self.Quote_list.horizontalHeaderItem(2)
        item.setText(_translate("Quote_check", "总数量"))
        item = self.Quote_list.horizontalHeaderItem(3)
        item.setText(_translate("Quote_check", "总价"))
        item = self.Quote_list.horizontalHeaderItem(4)
        item.setText(_translate("Quote_check", "业务员"))
        item = self.Quote_list.horizontalHeaderItem(5)
        item.setText(_translate("Quote_check", "报价日期"))
        item = self.Quote_list.horizontalHeaderItem(6)
        item.setText(_translate("Quote_check", "状态"))
        self.Quote_detail.setToolTip(_translate("Quote_check", "报价明细"))
        item = self.Quote_detail.horizontalHeaderItem(0)
        item.setText(_translate("Quote_check", "公司名称"))
        item = self.Quote_detail.horizontalHeaderItem(1)
        item.setText(_translate("Quote_check", "报价单号"))
        item = self.Quote_detail.horizontalHeaderItem(2)
        item.setText(_translate("Quote_check", "序号"))
        item = self.Quote_detail.horizontalHeaderItem(3)
        item.setText(_translate("Quote_check", "名称"))
        item = self.Quote_detail.horizontalHeaderItem(4)
        item.setText(_translate("Quote_check", "制造标准"))
        item = self.Quote_detail.horizontalHeaderItem(5)
        item.setText(_translate("Quote_check", "规格型号"))
        item = self.Quote_detail.horizontalHeaderItem(6)
        item.setText(_translate("Quote_check", "材质"))
        item = self.Quote_detail.horizontalHeaderItem(7)
        item.setText(_translate("Quote_check", "数量"))
        item = self.Quote_detail.horizontalHeaderItem(8)
        item.setText(_translate("Quote_check", "工作令号"))
        item = self.Quote_detail.horizontalHeaderItem(9)
        item.setText(_translate("Quote_check", "件号"))
        item = self.Quote_detail.horizontalHeaderItem(10)
        item.setText(_translate("Quote_check", "单价"))
        item = self.Quote_detail.horizontalHeaderItem(11)
        item.setText(_translate("Quote_check", "总价"))
        item = self.Quote_detail.horizontalHeaderItem(12)
        item.setText(_translate("Quote_check", "单重"))
        item = self.Quote_detail.horizontalHeaderItem(13)
        item.setText(_translate("Quote_check", "公斤价"))
        item = self.Quote_detail.horizontalHeaderItem(14)
        item.setText(_translate("Quote_check", "加工费"))
        item = self.Quote_detail.horizontalHeaderItem(15)
        item.setText(_translate("Quote_check", "其他费用"))
        item = self.Quote_detail.horizontalHeaderItem(16)
        item.setText(_translate("Quote_check", "备注"))

import erp_rc
